### ISSUE TITLE
[SUBMISSION]: Web Publishing with Github Pages and Quarto

### ISSUE THREAD

**Issue by liamodwyer** [libereurope/ds-essentials#16]
### Title

Web Publishing with Github Pages and Quarto

### Summary

A guide to Github focusing on its capabilities for web publishing.

### Contributors

Liam O'Dwyer | ORCiD: 0009-0006-8875-1002

### Submission Date

2024-06-17

### Related Topics

<1. Topic 1>

### Link to Google Doc

https://docs.google.com/document/d/1K4HF8daiAJXVVYfERzENqTbeoc4jhE0XGYzwSa8p1SY/edit#heading=h.q2tkcabgv2bj

### Access Requirements

- [ ] Yes, I would like to restrict access to the Google Doc.
- [X] No, there is no need to restrict access to the Google Doc.

### Submission Checklist

- [ ] Learning Objectives
- [x] Introduction to the Topic
- [x] Relevance to the Library Sector
- [x] Hands-On Activity & Other Self-Guided Tutorials
- [x] Recommended Reading & Viewing
- [ ] Taking Next Steps

### comments

<status update / action points / comments / to-dos / notes>

**Comment by noramcgregor** [comment]
Complete!
