### ISSUE TITLE
Incorrect Wikidata URIs on "Linked Open Data in Library Use Today" page

### ISSUE THREAD

**Issue by corined** [libereurope/ds-essentials#22]
The Wikidata URIs in the examples on the page "Linked Open Data in Library Use Today" do not identify the entity, but the page about the entity as the word _wiki_ in the URI path indicates. 

Wikidata URIs for entities follow this pattern http://www.wikidata.org/entity/[Q???]. See Section Linked Data Interface (URI) on this page https://www.wikidata.org/wiki/Wikidata:Data_access

Hence the URI for Miguel de Cervantes is http://www.wikidata.org/entity/Q5682 and the URI for El Quijote http://www.wikidata.org/entity/Q480

Thanks,

Corine

**Comment by noramcgregor** [comment]
Corine thank you so much for this! I'll pass this to the author now!

**Comment by noramcgregor** [comment]
Thank you @corined! Just caught up with the author and have revised it, thanks so much! Apologies for the delay!!
