### ISSUE TITLE
[SUBMISSION]: Working with Data #1 

### ISSUE THREAD

**Issue by NiamhCAMData** [libereurope/ds-essentials#7]
### Title

Working with Data

### Summary

To make library staff confident to be data workers, and to understand the key terminology. 

### Contributors

Niamh Malin [ORCID](https://orcid.org/0000-0002-4735-2113)

### Submission Date

<2024/05/14.

### Related Topics

<Data Visualisation >

### Link to Google Doc

https://docs.google.com/document/d/1HMSo1fJfbof_fTwULltm8wIPFU6p7tTXkKCfZb_OoN4/edit?pli=1#heading=h.q2tkcabgv2bj

### Access Requirements

- [ ] Yes, I would like to restrict access to the Google Doc.
- [ ] No, there is no need to restrict access to the Google Doc.

### Submission Checklist

- [ ] Learning Objectives
- [x] Introduction to the Topic
- [x] Relevance to the Library Sector
- [x] Hands-On Activity & Other Self-Guided Tutorials
- [x] Recommended Reading & Viewing
- [x] Taking Next Steps

### comments

Started the guide, breaking down where to find data and types of data. 
Plan to add definitions, data cycle, and find articles about uses of good data in library.

**Comment by noramcgregor** [comment]
Let me know when you're ready for a review in google and for me to move it to markdown :)

**Comment by NiamhCAMData** [comment]
The google doc is now ready for review, and can be moved to markdown :)

**Comment by noramcgregor** [comment]
Your markdown version is up! https://libereurope.github.io/ds-essentials/workingwdata.html Yay! It looks WONDERFUL thank you so much! Have a look at "what is data" section as I made a few minor edits there for clarity but happy to roll back or if you'd like to approach it differently feel VERY free to for the repository, make your edits there and submit a pull request for any changes/updates :)

**Comment by noramcgregor** [comment]
Complete!
