### ISSUE TITLE
[SUBMISSION]: Data Visualisation

### ISSUE THREAD

**Issue by harrylloyd-bl** [libereurope/ds-essentials#8]
### Title

Data Visualisation

### Summary

Why, when, and how should we visualise data?

### Contributors

Harry Lloyd, 0009-0009-3519-171X

### Submission Date

<YYYY-MM-DD>

### Related Topics

- Collections as Data
- Getting started in programming

### Link to Google Doc

https://docs.google.com/document/d/1zdhE7ewxoiyvUbvpj-k5S3sNMM0yKXPHFshQ1JDroIE/edit#heading=h.q2tkcabgv2bj

### Access Requirements

- [ ] Yes, I would like to restrict access to the Google Doc.
- [X] No, there is no need to restrict access to the Google Doc.

### Submission Checklist

- [ ] Learning Objectives
- [x] Introduction to the Topic
- [x] Relevance to the Library Sector
- [x] Hands-On Activity & Other Self-Guided Tutorials
- [x] Recommended Reading & Viewing
- [x] Taking Next Steps

### comments

Plan for content of guide filled out in doc
- Intro needs writing
- Relevance to lib sector needs an eg of exploratory data analysis either of a research output or e.g. a report on reader statistics
- hands on activity needs examples of non-code based visualisation e.g. excel/tableau/powerBI
- recommended reading and viewing has good examples but probably want a nice video demonstration of different data types
- taking next steps needs writing, some links to more philosophical docs and how to get started with the tools discussed

**Comment by harrylloyd-bl** [comment]
draft text mostly complete. needs one read through by me for sense check and flow, then ready to be reviewed and put into Markdown (which I'm happy to do myself)

**Comment by noramcgregor** [comment]
Made your page! https://github.com/libereurope/ds-essentials/blob/main/book/dataviz.qmd

**Comment by harrylloyd-bl** [comment]
Submitted PR for first draft :)

**Comment by noramcgregor** [comment]
OUTSTANDING!! This is excellently written and so informative thanks so much Harry! Just the most minor of suggestions/edits:

- Where you mention linked data you can now pop a link into our new Linked Open Data page! https://libereurope.github.io/ds-essentials/lod.html 

- We need a new title I reckon. Maybe something like Data Viz for Exploration and Explanation ?! Or something snappier if you can fashion it ha! 

- Just run through and make sure all the links are in there, spotted some missing like: Peripleo

Under the Hands On section:
- Would re-order that in terms of difficulty, so maybe swap the spreadsheet one around with the Intro to coding
- Can we add reference to this in the Power BI hands-on activity? https://justin.kelly.org.au/introduction-to-powerbi-for-librarians/ 
- Would be great to find a hands-on library data specific tutorial for the mapping and linked data section....maybe something relevant from in here: https://campus.dariah.eu/tag/data-visualisation

**Comment by harrylloyd-bl** [comment]
Addressed in new PR  :)

**Comment by noramcgregor** [comment]
Complete!!
